# spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
# spring.datasource.username=${MYSQLUSER}
# spring.datasource.password=${MYSQLPASSWORD}

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# # server.port=${PORT:8080}
# server.port=10000
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=nsbhavya83@gmail.com
# spring.mail.password=yvqu flhg kjtv hugv
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nsbhavya83@gmail.com
spring.mail.password=yvqu flhg kjtv hugv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

